import jsPDF from "jspdf";
import "jspdf-autotable";

export const generateEstimatePDF = (estimate) => {
  const doc = new jsPDF();

  // --- HEADER SECTION ---
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("OVERDRIVE AUTO SHOP", 14, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${estimate.branch_name} Branch`, 14, 28);
  doc.text(`Address: ${estimate.address || "N/A"}`, 14, 34);
  doc.text(
    `TIN: ${estimate.tin || "N/A"} | Contact: ${estimate.contact_number || "N/A"}`,
    14,
    40,
  );

  // --- ESTIMATE DETAILS (Right Side) ---
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("OFFICIAL ESTIMATE", 140, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Ref No: ${estimate.reference_number}`, 140, 28);
  doc.text(
    `Date: ${new Date(estimate.created_at).toLocaleDateString()}`,
    140,
    34,
  );
  doc.text(
    `Valid Until: ${new Date(estimate.expires_at).toLocaleDateString()}`,
    140,
    40,
  );

  // --- CUSTOMER & VEHICLE INFO ---
  doc.setLineWidth(0.5);
  doc.line(14, 45, 196, 45); // Horizontal line

  doc.setFont("helvetica", "bold");
  doc.text("Billed To:", 14, 52);
  doc.setFont("helvetica", "normal");
  doc.text(estimate.customer_name, 14, 58);

  doc.setFont("helvetica", "bold");
  doc.text("Vehicle Details:", 100, 52);
  doc.setFont("helvetica", "normal");
  doc.text(
    `${estimate.make} ${estimate.model} (${estimate.year || "N/A"})`,
    100,
    58,
  );
  doc.text(`Plate No: ${estimate.plate_number}`, 100, 64);
  doc.text(`Odometer: ${estimate.check_in_odometer || 0} km`, 100, 70);

  // --- LINE ITEMS TABLE ---
  const tableData = estimate.items.map((item) => [
    item.is_labor ? "Labor" : "Part",
    item.description,
    item.quantity,
    `PHP ${parseFloat(item.unit_cost).toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    `PHP ${parseFloat(item.total_price).toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
  ]);

  doc.autoTable({
    startY: 80,
    head: [["Type", "Description", "Qty", "Unit Price", "Total Price"]],
    body: tableData,
    theme: "grid",
    headStyles: { fillColor: [15, 23, 42], textColor: 255 }, // Dark Slate header
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 20 },
      2: { halign: "center", cellWidth: 15 },
      3: { halign: "right", cellWidth: 35 },
      4: { halign: "right", cellWidth: 35 },
    },
  });

  // --- TOTALS SECTION ---
  const finalY = doc.lastAutoTable.finalY + 10;
  const subtotal =
    parseFloat(estimate.total_amount) - parseFloat(estimate.tax_amount);

  doc.setFont("helvetica", "normal");
  doc.text("Subtotal:", 130, finalY);
  doc.text(
    `PHP ${subtotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    160,
    finalY,
    { align: "left" },
  );

  doc.text("VAT (12%):", 130, finalY + 6);
  doc.text(
    `PHP ${parseFloat(estimate.tax_amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    160,
    finalY + 6,
    { align: "left" },
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Grand Total:", 130, finalY + 14);
  doc.text(
    `PHP ${parseFloat(estimate.total_amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    160,
    finalY + 14,
    { align: "left" },
  );

  // --- FOOTER ---
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(
    "This is a non-posting estimate. Prices are subject to change after the validity date.",
    14,
    280,
  );
  doc.text("Generated by Overdrive Auto Shop System", 14, 285);

  // Trigger Download
  doc.save(`${estimate.reference_number}_Quote.pdf`);
};
