import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Save, Loader2, Wrench, MapPin } from "lucide-react";
import { MECHANIC_SPECIALTIES } from "../../../constants/specialties";

const MechanicModal = ({
  isOpen,
  onClose,
  onSubmit,
  initialData,
  branches = [],
}) => {
  const isEditing = !!initialData;
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    first_name: "",
    last_name: "",
    phone_number: "",
    branch_id: "",
    skills: [],
    status: "Active",
  });

  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setFormData({
          first_name: initialData.first_name,
          last_name: initialData.last_name,
          phone_number: initialData.phone_number || "",
          branch_id: initialData.branch_id || "",
          skills: initialData.skills || [],
          status: initialData.status || "Active",
        });
      } else {
        setFormData({
          first_name: "",
          last_name: "",
          phone_number: "",
          branch_id: branches.length > 0 ? branches[0].id : "",
          skills: [],
          status: "Active",
        });
      }
    }
  }, [isOpen, initialData, branches]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const toggleSkill = (skill) => {
    setFormData((prev) => {
      const hasSkill = prev.skills.includes(skill);
      let newSkills;
      if (hasSkill) {
        newSkills = prev.skills.filter((s) => s !== skill);
      } else {
        newSkills = [...prev.skills, skill];
      }
      return { ...prev, skills: newSkills };
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (formData.skills.length === 0) {
      return alert("Please select at least one skill specialty.");
    }

    setIsSubmitting(true);
    try {
      await onSubmit({
        ...formData,
        branch_id: parseInt(formData.branch_id, 10),
      });
    } catch (error) {
      alert(error.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="bg-white dark:bg-slate-800 rounded-3xl w-full max-w-2xl shadow-2xl border border-slate-200 dark:border-white/10 overflow-hidden max-h-[90vh] flex flex-col"
          >
            <div className="p-6 border-b border-slate-100 dark:border-white/5 flex justify-between items-center bg-slate-50 dark:bg-black/20 shrink-0">
              <div>
                <h2 className="text-xl font-black text-slate-900 dark:text-white uppercase italic tracking-tight flex items-center gap-2">
                  <Wrench className="text-amber-500" size={24} />
                  {isEditing ? "Edit Technician Profile" : "Enroll Technician"}
                </h2>
                <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-1">
                  Human Resource & Skill Assignment
                </p>
              </div>
              <button
                onClick={onClose}
                className="p-2 text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-white/10 rounded-xl transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            <div className="overflow-y-auto p-6">
              <form
                id="mechanicForm"
                onSubmit={handleSubmit}
                className="space-y-6"
              >
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      Employee ID
                    </label>
                    <div className="w-full bg-slate-100 dark:bg-slate-900/80 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm font-mono text-slate-500 flex items-center">
                      {/* Show the ID if editing, show "Auto-generated" if creating */}
                      {isEditing
                        ? initialData.employee_id
                        : "Auto-Generated by System"}
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2 flex items-center gap-1">
                      <MapPin size={12} className="text-blue-500" /> Branch
                      Assignment
                    </label>
                    <select
                      name="branch_id"
                      required
                      value={formData.branch_id}
                      onChange={handleChange}
                      className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm text-slate-900 dark:text-white focus:ring-2 focus:ring-amber-500 outline-none"
                    >
                      <option value="" disabled>
                        Select a branch
                      </option>
                      {branches.map((b) => (
                        <option key={b.id} value={b.id}>
                          {b.branch_code} - {b.branch_name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      First Name
                    </label>
                    <input
                      type="text"
                      name="first_name"
                      required
                      placeholder="Juan"
                      value={formData.first_name}
                      onChange={handleChange}
                      className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm text-slate-900 dark:text-white focus:ring-2 focus:ring-amber-500 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      Last Name
                    </label>
                    <input
                      type="text"
                      name="last_name"
                      required
                      placeholder="Dela Cruz"
                      value={formData.last_name}
                      onChange={handleChange}
                      className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm text-slate-900 dark:text-white focus:ring-2 focus:ring-amber-500 outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      Phone
                    </label>
                    <input
                      type="text"
                      name="phone_number"
                      placeholder="09XX..."
                      value={formData.phone_number}
                      onChange={handleChange}
                      className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm font-mono text-slate-900 dark:text-white focus:ring-2 focus:ring-amber-500 outline-none"
                    />
                  </div>
                </div>

                <div className="bg-slate-50 dark:bg-white/5 p-4 rounded-xl border border-slate-200 dark:border-white/10">
                  <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-3">
                    Skill Tags (Select all that apply)
                  </label>
                  <div className="flex flex-wrap gap-2">
                    {MECHANIC_SPECIALTIES.map((skill) => {
                      const isSelected = formData.skills.includes(skill);
                      return (
                        <button
                          type="button"
                          key={skill}
                          onClick={() => toggleSkill(skill)}
                          className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all border ${isSelected ? "bg-amber-500 text-slate-900 border-amber-500 shadow-md scale-105" : "bg-white dark:bg-slate-800 text-slate-500 border-slate-200 dark:border-white/10 hover:border-amber-500/50"}`}
                        >
                          {skill}
                        </button>
                      );
                    })}
                  </div>
                </div>

                {isEditing && (
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-widest text-slate-500 mb-2">
                      Employment Status
                    </label>
                    <select
                      name="status"
                      value={formData.status}
                      onChange={handleChange}
                      className="w-full bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-sm text-slate-900 dark:text-white focus:ring-2 focus:ring-amber-500 outline-none"
                    >
                      <option value="Active">
                        Active (Available for Work)
                      </option>
                      <option value="On Leave">
                        On Leave (Temporarily Unavailable)
                      </option>
                      <option value="Inactive">
                        Inactive (Resigned / Terminated)
                      </option>
                    </select>
                  </div>
                )}
              </form>
            </div>

            <div className="p-6 border-t border-slate-100 dark:border-white/5 flex gap-3 shrink-0">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="flex-1 px-4 py-3 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                form="mechanicForm"
                disabled={isSubmitting}
                className="flex-1 px-4 py-3 bg-amber-500 hover:bg-amber-600 text-slate-900 rounded-xl text-[10px] font-black uppercase tracking-widest transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {isSubmitting ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <Save size={16} />
                )}
                {isEditing ? "Save Profile" : "Enroll Mechanic"}
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default MechanicModal;
