import React, { useState, useMemo } from "react";
import {
  Scale,
  Calendar,
  MapPin,
  EyeOff,
  Eye,
  Download,
  ShieldCheck,
  AlertTriangle,
  ExternalLink,
} from "lucide-react";

// --- DUMMY DATA FOR MOCKUP ---
// In production, this is generated by a SQL SUM() query grouped by account_id
const MOCK_TRIAL_BALANCE = [
  // Assets (1000s) - Normal Balance: Debit
  {
    code: "1000",
    name: "Cash-on-Hand",
    type: "Asset",
    debit: 150000.0,
    credit: 0,
  },
  {
    code: "1100",
    name: "Cash in Bank",
    type: "Asset",
    debit: 450000.0,
    credit: 0,
  },
  {
    code: "1200",
    name: "Accounts Receivable",
    type: "Asset",
    debit: 450000.0,
    credit: 0,
  }, // Adjusted for balance
  {
    code: "1300",
    name: "Inventory Assets",
    type: "Asset",
    debit: 320000.0,
    credit: 0,
  },
  { code: "1400", name: "Prepaid Rent", type: "Asset", debit: 0, credit: 0 }, // Zero balance example

  // Liabilities (2000s) - Normal Balance: Credit
  {
    code: "2000",
    name: "Accounts Payable",
    type: "Liability",
    debit: 0,
    credit: 115000.0,
  },
  {
    code: "2100",
    name: "Output VAT Payable",
    type: "Liability",
    debit: 0,
    credit: 35000.0,
  },

  // Equity (3000s) - Normal Balance: Credit
  {
    code: "3000",
    name: "Owner's Capital",
    type: "Equity",
    debit: 0,
    credit: 500000.0,
  },
  {
    code: "3100",
    name: "Retained Earnings",
    type: "Equity",
    debit: 0,
    credit: 150000.0,
  },

  // Revenue (4000s) - Normal Balance: Credit
  {
    code: "4000",
    name: "Labor Revenue",
    type: "Revenue",
    debit: 0,
    credit: 825000.0,
  },

  // Expenses (5000s) - Normal Balance: Debit
  {
    code: "5000",
    name: "Cost of Goods Sold",
    type: "Expense",
    debit: 180000.0,
    credit: 0,
  },
  {
    code: "5100",
    name: "Salaries & Wages",
    type: "Expense",
    debit: 60000.0,
    credit: 0,
  },
  {
    code: "5200",
    name: "Utilities Expense",
    type: "Expense",
    debit: 15000.0,
    credit: 0,
  },
];

const formatCurrency = (amount) => {
  if (amount === 0 || !amount) return "-";
  return new Intl.NumberFormat("en-PH", {
    style: "currency",
    currency: "PHP",
  }).format(amount);
};

const TrialBalance = () => {
  // --- STATE ---
  const [selectedBranch, setSelectedBranch] = useState("All");
  const [asOfDate, setAsOfDate] = useState(
    new Date().toISOString().split("T")[0],
  );
  const [hideZeroBalances, setHideZeroBalances] = useState(true);

  // --- LOGIC ---
  const filteredAccounts = useMemo(() => {
    return MOCK_TRIAL_BALANCE.filter((acc) => {
      if (hideZeroBalances && acc.debit === 0 && acc.credit === 0) return false;
      return true;
    });
  }, [hideZeroBalances]);

  const totals = useMemo(() => {
    return filteredAccounts.reduce(
      (acc, row) => {
        acc.debit += row.debit;
        acc.credit += row.credit;
        return acc;
      },
      { debit: 0, credit: 0 },
    );
  }, [filteredAccounts]);

  const isBalanced = Math.abs(totals.debit - totals.credit) < 0.01;

  return (
    <div className="space-y-6 animate-in fade-in duration-700 pb-10 relative">
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-slate-800 p-6 rounded-3xl border border-slate-200 dark:border-white/10 shadow-sm">
        <div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight uppercase italic flex items-center gap-3">
            <Scale className="text-indigo-500" size={28} />
            Trial Balance
          </h1>
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-1">
            Unadjusted Financial Verification Report
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-3 w-full md:w-auto">
          <button className="flex-1 md:flex-none px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-black uppercase tracking-widest flex items-center justify-center gap-2 transition-all shadow-[0_0_15px_rgba(79,70,229,0.3)]">
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      {/* FILTER CONTROLS */}
      <div className="flex flex-col sm:flex-row gap-4 bg-white dark:bg-slate-800 p-4 rounded-2xl border border-slate-200 dark:border-white/10 shadow-sm">
        {/* As Of Date */}
        <div className="relative flex-1">
          <Calendar
            className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
            size={16}
          />
          <input
            type="date"
            value={asOfDate}
            onChange={(e) => setAsOfDate(e.target.value)}
            className="w-full pl-10 pr-4 py-3 bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl text-sm font-bold text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-indigo-500 transition-all"
          />
        </div>

        {/* Branch Filter */}
        <div className="relative flex-1">
          <MapPin
            className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
            size={16}
          />
          <select
            value={selectedBranch}
            onChange={(e) => setSelectedBranch(e.target.value)}
            className="w-full pl-10 pr-4 py-3 bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl text-sm font-bold text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-indigo-500 transition-all appearance-none"
          >
            <option value="All">Consolidated (All Branches)</option>
            <option value="Calamba">Calamba Branch</option>
            <option value="Batino">Batino Branch</option>
            <option value="Biñan">Biñan Branch</option>
          </select>
        </div>

        {/* Hide Zero Balance Toggle */}
        <button
          onClick={() => setHideZeroBalances(!hideZeroBalances)}
          className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-xs font-black uppercase tracking-widest transition-all border ${
            hideZeroBalances
              ? "bg-slate-900 text-white dark:bg-white dark:text-slate-900 border-transparent"
              : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400 border-slate-200 dark:border-white/10"
          }`}
        >
          {hideZeroBalances ? <EyeOff size={16} /> : <Eye size={16} />}
          {hideZeroBalances ? "Hidden Zeros" : "Show Zeros"}
        </button>
      </div>

      {/* TRIAL BALANCE REPORT TABLE */}
      <div className="bg-white dark:bg-slate-800 rounded-3xl border border-slate-200 dark:border-white/10 shadow-sm overflow-hidden">
        {/* Report Header Label */}
        <div className="p-6 border-b border-slate-200 dark:border-white/10 text-center bg-slate-50 dark:bg-slate-900/50">
          <h2 className="text-lg font-black text-slate-900 dark:text-white uppercase tracking-widest">
            Overdrive Auto Shop
          </h2>
          <p className="text-xs font-bold text-slate-500 mt-1 uppercase tracking-widest">
            Trial Balance •{" "}
            {selectedBranch === "All" ? "Consolidated" : selectedBranch}
          </p>
          <p className="text-[10px] font-mono text-slate-400 mt-1">
            As of{" "}
            {new Date(asOfDate).toLocaleDateString("en-US", {
              month: "long",
              day: "numeric",
              year: "numeric",
            })}
          </p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-100 dark:bg-black/20 text-[10px] font-black uppercase tracking-widest text-slate-500 border-b border-slate-200 dark:border-white/10">
                <th className="p-4 w-24">Code</th>
                <th className="p-4">Account Title</th>
                <th className="p-4 text-right w-48">Debit Balance (₱)</th>
                <th className="p-4 text-right w-48">Credit Balance (₱)</th>
              </tr>
            </thead>
            <tbody className="text-sm font-medium text-slate-700 dark:text-slate-300 divide-y divide-slate-100 dark:divide-white/5">
              {filteredAccounts.map((acc) => (
                <tr
                  key={acc.code}
                  className="hover:bg-slate-50 dark:hover:bg-white/5 transition-colors group"
                >
                  <td className="p-4 font-mono text-slate-400 text-xs">
                    {acc.code}
                  </td>
                  <td className="p-4 flex items-center justify-between">
                    <div>
                      <span className="font-bold text-slate-900 dark:text-white">
                        {acc.name}
                      </span>
                      <span className="block text-[10px] text-slate-400 font-mono mt-0.5">
                        {acc.type}
                      </span>
                    </div>
                    {/* Drill-down link visible on hover */}
                    <button
                      className="opacity-0 group-hover:opacity-100 text-indigo-500 hover:text-indigo-600 transition-opacity p-1"
                      title="View Ledger"
                    >
                      <ExternalLink size={14} />
                    </button>
                  </td>
                  <td className="p-4 text-right font-mono text-slate-800 dark:text-slate-200">
                    {formatCurrency(acc.debit)}
                  </td>
                  <td className="p-4 text-right font-mono text-slate-800 dark:text-slate-200">
                    {formatCurrency(acc.credit)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* THE BALANCE LOCK FOOTER */}
        <div
          className={`p-6 border-t flex flex-col md:flex-row justify-between items-center gap-4 transition-colors ${
            isBalanced
              ? "bg-emerald-50/50 border-emerald-200 dark:bg-emerald-900/10 dark:border-emerald-500/30"
              : "bg-rose-50/50 border-rose-200 dark:bg-rose-900/10 dark:border-rose-500/30"
          }`}
        >
          <div className="flex items-center gap-3">
            {isBalanced ? (
              <div className="p-2 bg-emerald-100 dark:bg-emerald-500/20 rounded-full">
                <ShieldCheck
                  size={24}
                  className="text-emerald-600 dark:text-emerald-400"
                />
              </div>
            ) : (
              <div className="p-2 bg-rose-100 dark:bg-rose-500/20 rounded-full">
                <AlertTriangle
                  size={24}
                  className="text-rose-600 dark:text-rose-400"
                />
              </div>
            )}
            <div>
              <h3
                className={`text-sm font-black uppercase tracking-widest ${
                  isBalanced
                    ? "text-emerald-700 dark:text-emerald-400"
                    : "text-rose-700 dark:text-rose-400"
                }`}
              >
                {isBalanced
                  ? "Ledger is in Balance"
                  : "Critical Integrity Error"}
              </h3>
              <p className="text-[10px] font-bold text-slate-500 mt-0.5">
                {isBalanced
                  ? "Total Debits match Total Credits."
                  : "Accounting equation broken. Investigate immediately."}
              </p>
            </div>
          </div>

          <div className="flex gap-8 w-full md:w-auto justify-between md:justify-end">
            <div className="text-right border-b-[3px] border-double border-slate-300 dark:border-slate-600 pb-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1">
                Total Debits
              </p>
              <p
                className={`text-xl font-mono font-black ${isBalanced ? "text-emerald-600 dark:text-emerald-400" : "text-rose-600 dark:text-rose-400"}`}
              >
                {formatCurrency(totals.debit)}
              </p>
            </div>
            <div className="text-right border-b-[3px] border-double border-slate-300 dark:border-slate-600 pb-1">
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1">
                Total Credits
              </p>
              <p
                className={`text-xl font-mono font-black ${isBalanced ? "text-emerald-600 dark:text-emerald-400" : "text-rose-600 dark:text-rose-400"}`}
              >
                {formatCurrency(totals.credit)}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TrialBalance;
